ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DOCUMENT_VIEW';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_ROLE_CHANGE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_DISABLE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_ENABLE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ONBOARDING_INVITE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ONBOARDING_COMPLETE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BRANDING_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MANAGER_ASSIGNMENT';

ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "tokenVersion" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "firstName" TEXT,
  ADD COLUMN IF NOT EXISTS "lastName" TEXT;

ALTER TABLE "Employee"
  ADD COLUMN IF NOT EXISTS "email" TEXT;

CREATE TABLE IF NOT EXISTS "ManagerAssignment" (
  "id" TEXT NOT NULL,
  "managerId" TEXT NOT NULL,
  "employeeId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ManagerAssignment_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "ManagerAssignment_managerId_employeeId_key" UNIQUE ("managerId", "employeeId"),
  CONSTRAINT "ManagerAssignment_managerId_fkey" FOREIGN KEY ("managerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "ManagerAssignment_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "ManagerAssignment_managerId_idx" ON "ManagerAssignment"("managerId");
CREATE INDEX IF NOT EXISTS "ManagerAssignment_employeeId_idx" ON "ManagerAssignment"("employeeId");
